- name: Install taskd
  become: true
  apt:
    pkg:
      - g++
      - libgnutls28-dev
      - uuid-dev
      - cmake
      - gnutls-bin

- name: Download taskd
  get_url:
    url: https://taskwarrior.org/download/taskd-1.1.0.tar.gz
    dest: /data/taskd-1.1.0.tar.gz
    checksum: sha1:ded339deeee65277e4712f71a9159502f8b20b52

- name: Extract taskd-1.1.0.tar.gz into /data/taskd-1.1.0
  unarchive:
    src: /data/taskd-1.1.0.tar.gz
    dest: /data
    remote_src: yes
  args:
    creates: /data/taskd-1.1.0

- name: Build taskd
  shell: |
    cd /data/taskd-1.1.0
    cmake -DCMAKE_BUILD_TYPE=release .
    make
    sudo make install
  args:
    creates: /usr/local/bin/taskd

- name: Ensure group "taskd" exists
  become: true
  ansible.builtin.group:
    name: taskd
    state: present

- name: Add the user 'taskd' with a primary group of 'taskd'
  become: true
  ansible.builtin.user:
    name: taskd
    group: taskd
    home: /data/taskd
    shell: /usr/sbin/nologin

- name: Create data location
  become: true
  ansible.builtin.file:
    path: /data/taskd
    owner: taskd
    group: taskd
    state: directory
    mode: '0755'

- name: Initialize
  ansible.builtin.command: taskd init
  environment:
    TASKDDATA: "{{ taskd_data }}"
  args:
    creates: $TASKDDATA/config

- name: Modify CN
  shell: sed -i 's/CN=localhost/CN={{ cn }}/' /data/taskd-1.1.0/pki/vars

- name: Generate certificates
  environment:
    TASKDDATA: "{{ taskd_data }}"
  shell: |
    cd /data/taskd-1.1.0/pki
    ./generate
    cp client.cert.pem $TASKDDATA
    cp client.key.pem $TASKDDATA
    cp server.cert.pem $TASKDDATA
    cp server.key.pem $TASKDDATA
    cp server.crl.pem $TASKDDATA
    cp ca.cert.pem $TASKDDATA
  args:
    creates: /data/taskd-1.1.0/pki/ca.cert.pem

- name: Install acl
  become: true
  apt:
    pkg:
      - acl

- name: Configure Taskserver
  become: true
  environment:
    TASKDDATA: "{{ taskd_data }}"
  shell: |
    taskd config --force client.cert $TASKDDATA/client.cert.pem
    taskd config --force client.key $TASKDDATA/client.key.pem
    taskd config --force server.cert $TASKDDATA/server.cert.pem
    taskd config --force server.key $TASKDDATA/server.key.pem
    taskd config --force server.crl $TASKDDATA/server.crl.pem
    taskd config --force ca.cert $TASKDDATA/ca.cert.pem

- name: Control with SystemD
  become: true
  shell: |
    cd /data/taskd-1.1.0/scripts/systemd
    sed -i 's|/usr/bin/taskd|/usr/local/bin/taskd|' taskd.service
    sed -i 's|/var/lib/taskd|/data/taskd|' taskd.service
    cp taskd.service /etc/systemd/system

- name: Enable and start taskd
  become: true
  systemd:
    name: taskd.service
    enabled: true
    state: started
    daemon_reload: true

- name: Create org
  become: true
  environment:
    TASKDDATA: "{{ taskd_data }}"
  command: taskd add org Public
  args:
    creates: $TASKDDATA/orgs/Public
  register: org_added
    
- name: Create user
  become: true
  environment:
    TASKDDATA: "{{ taskd_data }}"
  command: taskd add user 'Public' 'Quan Tong'
  register: user_added
  when: org_added.changed

- name: Generate client cert
  become: true
  shell: |
    cd /data/taskd-1.1.0/pki
    ./generate.client quan_tong
  when: user_added.changed